### ISSUE TITLE
Bug in b64_to_ab64 wtihin the pbkdf2 password module

### ISSUE THREAD

**Issue by jroose** [winlibs/openldap#3]
The b64_to_ab64 function within the pbkdf2 password module is incorrect.  

When str[0] == '+' this function fails to convert that first character to a '.'

The file in question is here: master/contrib/slapd-modules/passwd/pbkdf2/pw-pbkdf2.c and occurs at line 70 in the current version of the file.

This occurs because when you write while (*p++), it changes the pointer and skips over the first character of str.  

This needs to be replaced with a for loop such as:
for(char* p = str; *p; p++)

This is a significant bug in this module, because it causes the hash algorithm to fail to be replicable by outside hash implementations 1/64 times, which is supper annoying.  It's especially bad if you're generating lots of users in which case this hard to track down bug would cause your user creation to fail 1/64 times.

**Comment by weltling** [comment]
Thanks for reporting. Please report this upstream.

Thanks.
