### ISSUE TITLE
Please update to 2.4.47

### ISSUE THREAD

**Issue by Jan-E** [winlibs/openldap#4]
@weltling Could you update Openldap to the latest version (2.4.47). This solved an issue with OpenSSL 1.1.1. See https://www.apachelounge.com/viewtopic.php?t=8168

**Comment by Jan-E** [comment]
https://www.apachelounge.com/viewtopic.php?p=37718#37718

My sources with +/- your patches:
https://phpdev.toolsforresearch.com/openldap-2.4.47.7z

**Comment by Jan-E** [comment]
Right, I see you took another road to fix OpenSSL 1.1.1 compatibility: https://github.com/winlibs/openldap/commit/a2a65a059f316153546e180261dddcb66f5396eb
Thanks,

**Comment by weltling** [comment]
Thanks for checking, @Jan-E. Still waiting on response https://bugs.php.net/bug.php?id=77440, lets see. An upgrade to 2.4.47 is perhaps too radical, but might be required if the patch doesn't work out.

Thanks.

**Comment by Jan-E** [comment]
I could not reproduce the problem myself. I just had to rely on feedback from the Apachelounge users at https://www.apachelounge.com/viewtopic.php?t=8168
